# Generated by Django 5.2.7 on 2025-10-18 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acquisti', '0001_initial'),
        ('contabilita', '0001_initial'),
        ('fatture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificativo del conto (es: Banca Intesa Conto Corrente)', max_length=100, verbose_name='Nome Conto')),
                ('tipo_conto', models.CharField(choices=[('bancario', 'Conto Bancario'), ('cassa', 'Cassa'), ('paypal', 'PayPal/Conto Online'), ('altro', 'Altro')], default='bancario', max_length=10, verbose_name='Tipo Conto')),
                ('intestatario', models.CharField(blank=True, max_length=200, verbose_name='Intestatario')),
                ('iban', models.CharField(blank=True, max_length=27, validators=[django.core.validators.RegexValidator(message='Inserire un IBAN valido', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='IBAN')),
                ('nome_banca', models.CharField(blank=True, max_length=100, verbose_name='Nome Banca')),
                ('attivo', models.BooleanField(default=True, help_text='Se deselezionato, il conto non sarà più utilizzabile per nuovi movimenti', verbose_name='Conto Attivo')),
                ('conto_contabile', models.OneToOneField(blank=True, limit_choices_to={'codice__startswith': '1.1.0'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilita.pianodeiconti', verbose_name='Conto Contabile Associato')),
            ],
            options={
                'verbose_name': 'Conto Bancario',
                'verbose_name_plural': 'Conti Bancari',
                'ordering': ['tipo_conto', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Incasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_incasso', models.DateField(default=django.utils.timezone.localdate, help_text="Data in cui è avvenuto materialmente l'incasso", verbose_name='Data Incasso')),
                ('importo_incassato', models.DecimalField(decimal_places=2, help_text='Importo effettivamente incassato', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo Incassato')),
                ('metodo_pagamento', models.CharField(choices=[('bonifico', 'Bonifico Bancario'), ('assegno', 'Assegno'), ('contanti', 'Contanti'), ('pos', 'Carta di Credito/POS'), ('ria', 'RID/Riba'), ('altro', 'Altro')], default='bonifico', max_length=10, verbose_name='Metodo di Pagamento')),
                ('note', models.TextField(blank=True, help_text="Eventuali note sull'incasso (riferimenti, causale, etc.)", verbose_name='Note')),
                ('conto_bancario', models.ForeignKey(help_text="Seleziona il conto su cui è stato incassato l'importo", on_delete=django.db.models.deletion.PROTECT, related_name='incassi', to='tesoreria.contobancario', verbose_name='Conto di Accredito')),
                ('scadenza', models.ForeignKey(help_text="Seleziona la scadenza a cui associare l'incasso", on_delete=django.db.models.deletion.CASCADE, related_name='incassi', to='fatture.scadenzafattura', verbose_name='Scadenza Fattura')),
            ],
            options={
                'verbose_name': 'Incasso',
                'verbose_name_plural': 'Incassi',
                'ordering': ['-data_incasso'],
            },
        ),
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data Pagamento')),
                ('importo_pagato', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo Pagato')),
                ('metodo_pagamento', models.CharField(choices=[('bonifico', 'Bonifico Bancario'), ('assegno', 'Assegno'), ('contanti', 'Contanti'), ('pos', 'Carta di Credito/POS'), ('ria', 'RID/Riba'), ('altro', 'Altro')], default='bonifico', max_length=10, verbose_name='Metodo di Pagamento')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('conto_bancario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spese', to='tesoreria.contobancario', verbose_name='Conto di Addebito')),
                ('scadenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='acquisti.scadenzafatturaacquisto', verbose_name='Scadenza Fattura di Acquisto')),
            ],
            options={
                'verbose_name': 'Spesa/Pagamento',
                'verbose_name_plural': 'Spese/Pagamenti',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
