# Generated by Django 5.2.7 on 2025-10-18 08:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificativo del conto (es: Banca Intesa Conto Corrente)', max_length=100, verbose_name='Nome Conto')),
                ('tipo_conto', models.CharField(choices=[('bancario', 'Conto Bancario'), ('cassa', 'Cassa'), ('paypal', 'PayPal/Conto Online'), ('altro', 'Altro')], default='bancario', max_length=10, verbose_name='Tipo Conto')),
                ('intestatario', models.CharField(blank=True, max_length=200, verbose_name='Intestatario')),
                ('iban', models.CharField(blank=True, max_length=27, validators=[django.core.validators.RegexValidator(message='Inserire un IBAN valido', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='IBAN')),
                ('nome_banca', models.CharField(blank=True, max_length=100, verbose_name='Nome Banca')),
                ('saldo_attuale', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Saldo Attuale')),
                ('attivo', models.BooleanField(default=True, help_text='Se deselezionato, il conto non sarà più utilizzabile per nuovi movimenti', verbose_name='Conto Attivo')),
            ],
            options={
                'verbose_name': 'Conto Bancario',
                'verbose_name_plural': 'Conti Bancari',
                'ordering': ['tipo_conto', 'nome'],
            },
        ),
    ]
