# Generated by Django 5.2.7 on 2025-10-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0003_popola_piano_dei_conti'),
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contobancario',
            name='conto_contabile',
            field=models.ForeignKey(blank=True, limit_choices_to={'codice__startswith': '1.1.0'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilita.pianodeiconti', verbose_name='Conto Contabile Associato'),
        ),
    ]
