# Generated by Django 5.2.7 on 2025-10-18 08:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatture', '0002_fattura_cliente'),
        ('tesoreria', '0002_crea_conti_iniziali'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_incasso', models.DateField(default=django.utils.timezone.now, help_text="Data in cui è avvenuto materialmente l'incasso", verbose_name='Data Incasso')),
                ('importo_incassato', models.DecimalField(decimal_places=2, help_text='Importo effettivamente incassato', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo Incassato')),
                ('metodo_pagamento', models.CharField(choices=[('bonifico', 'Bonifico Bancario'), ('assegno', 'Assegno'), ('contanti', 'Contanti'), ('pos', 'Carta di Credito/POS'), ('ria', 'RID/Riba'), ('altro', 'Altro')], default='bonifico', max_length=10, verbose_name='Metodo di Pagamento')),
                ('note', models.TextField(blank=True, help_text="Eventuali note sull'incasso (riferimenti, causale, etc.)", verbose_name='Note')),
                ('conto_bancario', models.ForeignKey(help_text="Seleziona il conto su cui è stato incassato l'importo", on_delete=django.db.models.deletion.PROTECT, related_name='incassi', to='tesoreria.contobancario', verbose_name='Conto di Accredito')),
                ('scadenza', models.ForeignKey(help_text="Seleziona la scadenza a cui associare l'incasso", on_delete=django.db.models.deletion.CASCADE, related_name='incassi', to='fatture.scadenzafattura', verbose_name='Scadenza Fattura')),
            ],
            options={
                'verbose_name': 'Incasso',
                'verbose_name_plural': 'Incassi',
                'ordering': ['-data_incasso'],
            },
        ),
    ]
