# Generated by Django 5.2.7 on 2025-10-18 11:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisti', '0001_initial'),
        ('tesoreria', '0003_incasso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incasso',
            name='data_incasso',
            field=models.DateField(default=django.utils.timezone.localdate, help_text="Data in cui è avvenuto materialmente l'incasso", verbose_name='Data Incasso'),
        ),
        migrations.CreateModel(
            name='Spesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data Pagamento')),
                ('importo_pagato', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo Pagato')),
                ('metodo_pagamento', models.CharField(choices=[('bonifico', 'Bonifico Bancario'), ('assegno', 'Assegno'), ('contanti', 'Contanti'), ('pos', 'Carta di Credito/POS'), ('ria', 'RID/Riba'), ('altro', 'Altro')], default='bonifico', max_length=10, verbose_name='Metodo di Pagamento')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('conto_bancario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spese', to='tesoreria.contobancario', verbose_name='Conto di Addebito')),
                ('scadenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamenti', to='acquisti.scadenzafatturaacquisto', verbose_name='Scadenza Fattura di Acquisto')),
            ],
            options={
                'verbose_name': 'Spesa/Pagamento',
                'verbose_name_plural': 'Spese/Pagamenti',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
