# Generated by Django 5.2.7 on 2025-10-18 09:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrazioneContabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registrazione', models.DateField(help_text='Data della operazione contabile', verbose_name='Data Registrazione')),
                ('descrizione', models.TextField(help_text="Descrizione dettagliata dell'operazione", verbose_name='Descrizione Operazione')),
                ('metodo_pagamento', models.CharField(choices=[('bonifico', 'Bonifico Bancario'), ('assegno', 'Assegno'), ('contanti', 'Contanti'), ('altro', 'Altro')], default='bonifico', max_length=10, verbose_name='Metodo di Pagamento')),
                ('riferimento', models.CharField(blank=True, help_text='Numero fattura, bolletta, etc.', max_length=50, verbose_name='Riferimento Documento')),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('registrata', 'Registrata'), ('stornata', 'Stornata')], default='bozza', max_length=10, verbose_name='Stato Registrazione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registrazione Contabile',
                'verbose_name_plural': 'Registrazioni Contabili',
                'ordering': ['-data_registrazione', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PianoDeiConti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(help_text='Codice del conto (es: 1.1.01, 2.2.03)', max_length=10, unique=True, verbose_name='Codice Conto')),
                ('descrizione', models.CharField(help_text='Descrizione completa del conto', max_length=200, verbose_name='Descrizione Conto')),
                ('classe', models.CharField(choices=[('patrimoniale', 'Conto Patrimoniale'), ('economico', 'Conto Economico'), ('ordine', "Conto d'Ordine")], max_length=12, verbose_name='Classe Conto')),
                ('natura', models.CharField(choices=[('dare', 'Dare (Attivo/Costi)'), ('avere', 'Avere (Passivo/Ricavi)')], max_length=5, verbose_name='Natura Conto')),
                ('attivo', models.BooleanField(default=True, help_text='Se deselezionato, il conto non sarà più utilizzabile', verbose_name='Conto Attivo')),
                ('sottoconto_di', models.ForeignKey(blank=True, help_text='Conto padre (per gerarchia)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sottoconti', to='contabilita.pianodeiconti', verbose_name='Sottoconto di')),
            ],
            options={
                'verbose_name': 'Conto del Piano dei Conti',
                'verbose_name_plural': 'Piano dei Conti',
                'ordering': ['codice'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoContabile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimento', models.CharField(choices=[('dare', 'Dare'), ('avere', 'Avere')], max_length=5, verbose_name='Tipo Movimento')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importo')),
                ('note', models.TextField(blank=True, help_text='Note specifiche per questo movimento', verbose_name='Note Movimento')),
                ('conto', models.ForeignKey(help_text='Conto interessato dal movimento', on_delete=django.db.models.deletion.PROTECT, to='contabilita.pianodeiconti', verbose_name='Conto')),
                ('registrazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimenti', to='contabilita.registrazionecontabile', verbose_name='Registrazione')),
            ],
            options={
                'verbose_name': 'Movimento Contabile',
                'verbose_name_plural': 'Movimenti Contabili',
                'ordering': ['registrazione', 'tipo_movimento'],
            },
        ),
    ]
