# Generated by Django 5.2.7 on 2025-10-18 13:00

from django.db import migrations

def popola_piano_dei_conti(apps, schema_editor):
    """
    Script per creare un piano dei conti completo per una piccola/media impresa.
    """
    PianoDeiConti = apps.get_model('contabilita', 'PianoDeiConti')
    
    conti_creati = {}
    
    conti_da_creare = [
        # PATRIMONIALI
        {'codice': '1', 'descrizione': 'ATTIVO', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': None},
        {'codice': '1.1', 'descrizione': 'ATTIVO CIRCOLANTE', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1'},
        {'codice': '1.1.01', 'descrizione': 'CASSA', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.1'},
        {'codice': '1.1.02', 'descrizione': 'BANCHE E POSTE', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.1'},
        {'codice': '1.1.03', 'descrizione': 'CREDITI VERSO CLIENTI', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.1'},
        {'codice': '1.1.04', 'descrizione': 'RIMANENZE DI MAGAZZINO', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.1'},
        {'codice': '1.1.05', 'descrizione': 'RATEI ATTIVI', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.1'},
        {'codice': '1.2', 'descrizione': 'ATTIVO IMMOBILIZZATO', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1'},
        {'codice': '1.2.01', 'descrizione': 'IMMOBILI', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.2'},
        {'codice': '1.2.02', 'descrizione': 'AUTOMEZZI', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.2'},
        {'codice': '1.2.03', 'descrizione': 'ATTREZZATURE', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.2'},
        {'codice': '1.2.04', 'descrizione': 'ARREDAMENTO', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.2'},
        {'codice': '1.2.05', 'descrizione': 'IMPIANTI', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.2'},
        {'codice': '1.2.06', 'descrizione': 'FONDO AMMORTAMENTO', 'classe': 'patrimoniale', 'natura': 'dare', 'sottoconto_di': '1.2'},
        {'codice': '2', 'descrizione': 'PASSIVO', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': None},
        {'codice': '2.1', 'descrizione': 'PASSIVO CORRENTE', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2'},
        {'codice': '2.1.01', 'descrizione': 'DEBITI VERSO FORNITORI', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2.1'},
        {'codice': '2.1.02', 'descrizione': 'DEBITI TRIBUTARI', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2.1'},
        {'codice': '2.1.03', 'descrizione': 'DEBITI VERSO BANCHE', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2.1'},
        {'codice': '2.1.04', 'descrizione': 'RATEI PASSIVI', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2.1'},
        {'codice': '2.2', 'descrizione': 'PATRIMONIO NETTO', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2'},
        {'codice': '2.2.01', 'descrizione': 'CAPITALE SOCIALE', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2.2'},
        {'codice': '2.2.02', 'descrizione': 'UTILE PERDITA ESERCIZIO', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2.2'},
        {'codice': '2.2.03', 'descrizione': 'RISERVE', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2.2'},
        {'codice': '2.2.04', 'descrizione': 'BILANCIO DI APERTURA', 'classe': 'patrimoniale', 'natura': 'avere', 'sottoconto_di': '2.2'},

        # ECONOMICI
        {'codice': '3', 'descrizione': 'COSTI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': None},
        {'codice': '3.1', 'descrizione': 'ACQUISTI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3'},
        {'codice': '3.1.01', 'descrizione': 'ACQUISTI MERCI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.1'},
        {'codice': '3.1.02', 'descrizione': 'ACQUISTI MATERIE PRIME', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.1'},
        {'codice': '3.1.03', 'descrizione': 'ACQUISTI MATERIALE CONSUMO', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.1'},
        {'codice': '3.2', 'descrizione': 'SERVIZI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3'},
        {'codice': '3.2.01', 'descrizione': 'SERVIZI ENERGETICI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.2.02', 'descrizione': 'AFFITTI E LOCAZIONI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.2.03', 'descrizione': 'MANUTENZIONI E RIPARAZIONI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.2.04', 'descrizione': 'SERVIZI TELEFONICI E INTERNET', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.2.05', 'descrizione': 'SERVIZI PROFESSIONALI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.2.06', 'descrizione': 'PUBBLICITÀ E MARKETING', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.2.07', 'descrizione': 'SPESE POSTALI E BANCARIE', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.2.08', 'descrizione': 'ASSICURAZIONI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.2.09', 'descrizione': 'SPESE VARIE E IMPREVISTI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.2'},
        {'codice': '3.3', 'descrizione': 'PERSONALE', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3'},
        {'codice': '3.3.01', 'descrizione': 'STIPENDI E SALARI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.3'},
        {'codice': '3.3.02', 'descrizione': 'CONTRIBUTI PREVIDENZIALI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.3'},
        {'codice': '3.3.03', 'descrizione': 'TRATTAMENTO DI FINE RAPPORTO', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.3'},
        {'codice': '3.3.04', 'descrizione': 'PREMI E INCENTIVI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.3'},
        {'codice': '3.4', 'descrizione': 'TRIBUTI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3'},
        {'codice': '3.4.01', 'descrizione': 'IMPOSTE DIRETTE', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.4'},
        {'codice': '3.4.02', 'descrizione': 'IMPOSTE INDIRETTE', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.4'},
        {'codice': '3.4.03', 'descrizione': 'ADDIZIONALI E ACCISE', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.4'},
        {'codice': '3.5', 'descrizione': 'AMMORTAMENTI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3'},
        {'codice': '3.5.01', 'descrizione': 'AMMORTAMENTO IMMOBILI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.5'},
        {'codice': '3.5.02', 'descrizione': 'AMMORTAMENTO AUTOMEZZI', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.5'},
        {'codice': '3.5.03', 'descrizione': 'AMMORTAMENTO ATTREZZATURE', 'classe': 'economico', 'natura': 'dare', 'sottoconto_di': '3.5'},
        {'codice': '4', 'descrizione': 'RICAVI', 'classe': 'economico', 'natura': 'avere', 'sottoconto_di': None},
        {'codice': '4.1', 'descrizione': 'RICAVI VENDITE', 'classe': 'economico', 'natura': 'avere', 'sottoconto_di': '4'},
        {'codice': '4.1.01', 'descrizione': 'RICAVI VENDITE PRODOTTI', 'classe': 'economico', 'natura': 'avere', 'sottoconto_di': '4.1'},
        {'codice': '4.1.02', 'descrizione': 'RICAVI VENDITE SERVIZI', 'classe': 'economico', 'natura': 'avere', 'sottoconto_di': '4.1'},
        {'codice': '4.1.03', 'descrizione': 'RICAVI ACCESSORI', 'classe': 'economico', 'natura': 'avere', 'sottoconto_di': '4.1'},
        {'codice': '4.2', 'descrizione': 'RICAVI FINANZIARI', 'classe': 'economico', 'natura': 'avere', 'sottoconto_di': '4'},
        {'codice': '4.2.01', 'descrizione': 'INTERESSI ATTIVI', 'classe': 'economico', 'natura': 'avere', 'sottoconto_di': '4.2'},
        {'codice': '4.2.02', 'descrizione': 'PROVENTI DIVERSI', 'classe': 'economico', 'natura': 'avere', 'sottoconto_di': '4.2'},

        # CONTI D'ORDINE
        {'codice': '5', 'descrizione': 'CONTI D\'ORDINE', 'classe': 'ordine', 'natura': 'dare', 'sottoconto_di': None},
        {'codice': '5.1', 'descrizione': 'GARANZIE RICEVUTE', 'classe': 'ordine', 'natura': 'dare', 'sottoconto_di': '5'},
        {'codice': '5.2', 'descrizione': 'GARANZIE CONCESSE', 'classe': 'ordine', 'natura': 'dare', 'sottoconto_di': '5'},
    ]
    
    for conto_data in conti_da_creare:
        codice = conto_data['codice']
        conto, created = PianoDeiConti.objects.get_or_create(
            codice=codice,
            defaults={
                'descrizione': conto_data['descrizione'],
                'classe': conto_data['classe'],
                'natura': conto_data['natura'],
            }
        )
        conti_creati[codice] = conto

    for conto_data in conti_da_creare:
        padre_codice = conto_data['sottoconto_di']
        if padre_codice:
            conto = conti_creati[conto_data['codice']]
            padre = conti_creati[padre_codice]
            if conto.sottoconto_di != padre:
                conto.sottoconto_di = padre
                conto.save()

class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popola_piano_dei_conti),
    ]

