# Generated by Django 5.2.7 on 2025-10-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0002_popola_piano_dei_conti'),
    ]

    operations = [
    ]
