# Generated by Django 5.2.7 on 2025-10-18 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilita', '0003_popola_piano_dei_conti'),
        ('tesoreria', '0002_alter_contobancario_conto_contabile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocontabile',
            name='conto_tesoreria',
            field=models.ForeignKey(blank=True, help_text='Il conto di tesoreria specifico (es. Banca Intesa) movimentato.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.contobancario', verbose_name='Conto Tesoreria Specifico'),
        ),
    ]
