# Generated by Django 5.2.7 on 2025-10-18 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Numero Fattura')),
                ('data_emissione', models.DateField(verbose_name='Data Emissione')),
                ('importo_totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo Totale Fattura')),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=22.0, max_digits=5, verbose_name='Aliquota IVA')),
                ('descrizione', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('bozza', 'Bozza'), ('emessa', 'Emessa'), ('parzialmente_pagata', 'Parzialmente Pagata'), ('pagata', 'Pagata')], default='bozza', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScadenzaFattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField(verbose_name='Data Scadenza Pagamento')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo Scadenza')),
                ('stato', models.CharField(choices=[('da_pagare', 'Da Pagare'), ('pagata', 'Pagata'), ('scaduta', 'Scaduta')], default='da_pagare', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Effettiva Pagamento')),
                ('fattura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze', to='fatture.fattura', verbose_name='Fattura di Riferimento')),
            ],
            options={
                'verbose_name': 'Scadenza Fattura',
                'verbose_name_plural': 'Scadenze Fatture',
                'ordering': ['data_scadenza'],
            },
        ),
    ]
