# Generated by Django 5.2.7 on 2025-10-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0001_initial'),
        ('fatture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='cliente',
            field=models.ForeignKey(default=1, help_text='Seleziona il cliente a cui intestare la fattura', on_delete=django.db.models.deletion.PROTECT, related_name='fatture', to='clienti.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
