# Generated by Django 5.2.7 on 2025-10-18 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornitori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatturaAcquisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero Fattura')),
                ('data_documento', models.DateField(verbose_name='Data Documento')),
                ('data_ricezione', models.DateField(default=django.utils.timezone.now, verbose_name='Data Ricezione')),
                ('importo_totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Imponibile')),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=22.0, max_digits=5, verbose_name='Aliquota IVA')),
                ('descrizione', models.TextField(blank=True)),
                ('stato', models.CharField(choices=[('da_registrare', 'Da Registrare'), ('registrata', 'Registrata'), ('parzialmente_pagata', 'Parzialmente Pagata'), ('pagata', 'Pagata')], default='da_registrare', max_length=20)),
                ('fornitore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fatture_acquisto', to='fornitori.fornitore', verbose_name='Fornitore')),
            ],
            options={
                'verbose_name': 'Fattura di Acquisto',
                'verbose_name_plural': 'Fatture di Acquisto',
                'ordering': ['-data_documento'],
            },
        ),
        migrations.CreateModel(
            name='ScadenzaFatturaAcquisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scadenza', models.DateField(verbose_name='Data Scadenza Pagamento')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo Scadenza')),
                ('stato', models.CharField(choices=[('da_pagare', 'Da Pagare'), ('parzialmente_pagata', 'Parzialmente Pagata'), ('pagata', 'Pagata')], default='da_pagare', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Effettivo Pagamento')),
                ('fattura_acquisto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scadenze_acquisto', to='acquisti.fatturaacquisto', verbose_name='Fattura di Riferimento')),
            ],
            options={
                'verbose_name': 'Scadenza Fattura di Acquisto',
                'verbose_name_plural': 'Scadenze Fatture di Acquisto',
                'ordering': ['data_scadenza'],
            },
        ),
    ]
