# Generated by Django 5.2.7 on 2025-10-18 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(help_text="Nome completo dell'azienda o della persona", max_length=200, verbose_name='Ragione Sociale')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('citta', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('cap', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Il CAP deve avere 5 numeri')], verbose_name='CAP')),
                ('provincia', models.CharField(blank=True, help_text='Sigla provincia (es: RM)', max_length=2, verbose_name='Provincia')),
                ('partita_iva', models.CharField(help_text='Partita IVA (11 cifre)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'La P.IVA deve avere 11 numeri')], verbose_name='Partita IVA')),
                ('codice_fiscale', models.CharField(blank=True, help_text='Codice Fiscale (16 caratteri)', max_length=16, verbose_name='Codice Fiscale')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('stato', models.CharField(choices=[('attivo', 'Attivo'), ('inattivo', 'Inattivo'), ('bloccato', 'Bloccato')], default='attivo', max_length=10, verbose_name='Stato Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
                'ordering': ['ragione_sociale'],
            },
        ),
    ]
